// Styles for CC text box
export var ccTextBoxCss = [
  ["position", "absolute"],
  ["top", null],
  ["right", null],
  ["bottom", "50px"],
  ["left", null],
  ["margin-top", null],
  ["margin-right", null],
  ["margin-bottom", null],
  ["margin-left", null],
  ["padding-top", null],
  ["padding-right", null],
  ["padding-bottom", null],
  ["padding-left", null],
  ["width", "1198px"],
  ["height", "75px"],
  ["background-color", "rgba(179, 150, 0, .865)"],
  ["color", null],
  ["overflow-y", "scroll"],
  ["overflow-x", null],
  ["z-index", 2000],
];

// Styles for CC text
export var ccParagraphCss = [
  ["position", "static"],
  ["top", null],
  ["right", null],
  ["bottom", null],
  ["left", null],
  ["margin-top", "5px"],
  ["margin-right", "16px"],
  ["margin-bottom", "5px"],
  ["margin-left", "16px"],
  ["padding-top", null],
  ["padding-right", null],
  ["padding-bottom", null],
  ["padding-left", null],
  ["width", null],
  ["height", null],
  ["color", "#000"],
  ["font-size", "18px"],
  ["font-family", "Myriad Pro"],
  ["font-weight", "700"],
  ["letter-spacing", "1px"],
  ["line-height", "24px"],
];
