export const noTimerSlidesArray = [];

export const durationTimeCss = [
  ["position", "absolute"],
  ["top", "95%"],
  ["right", null],
  ["bottom", null],
  ["left", "85%"],
  ["margin-top", null],
  ["margin-right", null],
  ["margin-bottom", null],
  ["margin-left", null],
  ["padding-top", null],
  ["padding-right", null],
  ["padding-bottom", null],
  ["padding-left", null],
  ["color", "white"],
  ["font-weight", "inherit"],
  ["font-family", "inherit"],
  ["font-size", "inherit"],
  ["z-index", 2000],
];

export const currentTimeCss = [
  ["position", "absolute"],
  ["top", "95%"],
  ["right", null],
  ["bottom", null],
  ["left", "9%"],
  ["margin-top", null],
  ["margin-right", null],
  ["margin-bottom", null],
  ["margin-left", null],
  ["padding-top", null],
  ["padding-right", null],
  ["padding-bottom", null],
  ["padding-left", null],
  ["color", "white"],
  ["font-weight", "inherit"],
  ["font-family", "inherit"],
  ["font-size", "inherit"],
  ["z-index", 2000],
];
